import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useAuth } from "@arcana/auth-react";
import { rpcURLnetwork, authArcana } from "../utils/authArcana";
import axios from "axios";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { user, connect, isLoggedIn, loading, loginWithSocial, provider } =
    useAuth();

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [lat, setLat] = useState("");
  const [long, setLong] = useState("");
  const [trueUser, setTrueUser] = useState(true);

  const onConnectClick = async () => {
    try {
      await connect();
    } catch (e) {
      console.log(e);
    }
  };

  const onConnect = async () => {
    await authArcana.init();
    const info = await authArcana.getUser();
    console.log(info);
    alert("You have successfully logged in " + info.email);
    // push to /home
    window.location.href = "/home";

  };

  const loginMetamask = () => {
    window.ethereum.request({ method: "eth_requestAccounts" }).then((res) => {
      // Return the address of the wallet
      console.log(res);
      alert("You have successfully logged in " + res[0]);
      window.location.href = "/home";
    });
  }

  const signInWithEmail = async (e) => {
    e.preventDefault();
    const time = new Date().getHours();
    console.log(time);

    await navigator.geolocation.getCurrentPosition(function (position) {
      console.log(position.coords.latitude);
      console.log(position.coords.longitude);
      setLat(position.coords.latitude);
      setLong(position.coords.longitude);
    });

    const ipapi = await fetch("https://ipapi.co/json/").then((res) =>
      res.json()
    );

    console.log(ipapi.ip);

    const body = {
      email,
      password,
      time,
      lat,
      long,
      ip: ipapi.ip,
    };
    // send a post request to https://nisproject.onrender.com/predict with time and ip in axios
    const res = await axios.post("https://nisproject.onrender.com/predict",  {
      login_time: time,
      ip_addr: ipapi.ip,
    }, {
      headers: {
        'Content-Type': 'application/json',
      }
    });

    console.log(res.data);
    if (res.data.status === "alert") {
      alert("You have been flagged for suspicious activity");
      setTrueUser(false);
    } else {
      alert("You have successfully logged in " + email + password + time);
      setTrueUser(true);
    }

    
  };

  useEffect(() => {
    provider.on("connect", onConnect);
    return () => {
      provider.removeListener("connect", onConnect);
    };
  }, [provider]);

  return (
    <>
      <Head>
        <title>Passwordless Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="grid h-screen w-screen place-items-center bg-slate-800 px-4 text-sm font-medium">
        <div class="w-full max-w-sm rounded-lg bg-slate-700/30 shadow">
          <div class="p-4 md:p-5 lg:p-6">
            {!trueUser ? (
              <>
                <p className="pt-2 pb-4 text-red-600">
                  {" "}
                  Suspicious Activity Detected
                </p>
                <p className="pb-5"> Two Factor Authentication Required</p>
                <div class="grid gap-y-3">
                  <button
                    class="flex items-center justify-center gap-x-2 rounded-md border border-slate-600 bg-slate-700 py-3 px-4 text-slate-300 transition hover:text-purple-400"
                    onClick={onConnectClick}
                  >
                    {/* <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="18"
                  height="18"
                  fill="currentColor"
                  class="bi bi-github"
                  viewBox="0 0 16 16"
                >
                  <path
                    d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"
                    fill="#cbd5e1"
                  ></path>
                </svg> */}
                    {/* <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="18"
                    height="18"
                    fill="currentColor"
                    class="bi bi-metamask"
                    viewBox="0 0 16 16"
                  >
                    <path
                      d="M8 0a8 8 0 0 0-8 8c0 4.418 5.373 8 8 8 2.627 0 8-3.582 8-8a8 8 0 0 0-8-8zm3.5 11.5a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-3a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5v3zm-1.5-4.5a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0v-1zm0 2a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0v-1z"
                      fill="#cbd5e1"
                    ></path>
                  </svg> */}
                    Sign in with passwordless Auth - Arcana
                  </button>
                  <button
                    class="flex items-center justify-center gap-x-2 rounded-md border border-slate-600 bg-slate-700 py-3 px-4 text-slate-300 transition hover:text-purple-400"
                    onClick={loginMetamask}
                  >
                    {/* <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="18"
                  height="18"
                  fill="currentColor"
                  class="bi bi-github"
                  viewBox="0 0 16 16"
                >
                  <path
                    d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"
                    fill="#cbd5e1"
                  ></path>
                </svg> */}
                    {/* <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="18"
                    height="18"
                    fill="currentColor"
                    class="bi bi-metamask"
                    viewBox="0 0 16 16"
                  >
                    <path
                      d="M8 0a8 8 0 0 0-8 8c0 4.418 5.373 8 8 8 2.627 0 8-3.582 8-8a8 8 0 0 0-8-8zm3.5 11.5a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-3a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5v3zm-1.5-4.5a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0v-1zm0 2a.5.5 0 0 0-1 0v1a.5.5 0 0 0 1 0v-1z"
                      fill="#cbd5e1"
                    ></path>
                  </svg> */}
                    Sign in with passwordless Auth - Metamask
                  </button>
                  {/* <button class="flex items-center justify-center gap-x-2 rounded-md border border-slate-600 bg-slate-700 py-3 px-4 text-slate-300 transition hover:text-purple-400">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="18"
                  height="18"
                  fill="currentColor"
                  class="bi bi-google"
                  viewBox="0 0 16 16"
                >
                  <path
                    d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z"
                    fill="#cbd5e1"
                  ></path>
                </svg>
                Sign in with Google
              </button> */}
                </div>
              </>
            ) : (
              <div class="grid gap-y-3">
                <input
                  class="focus:border-purple-400 rounded-md border border-slate-600 bg-slate-700 py-3 px-4 text-slate-200 outline-none transition placeholder:text-slate-400"
                  placeholder="email@example.com"
                  onChange={(e) => {
                    setEmail(e.target.value);
                  }}
                />
                <input
                  class="focus:border-purple-400 rounded-md border border-slate-600 bg-slate-700 py-3 px-4 text-slate-200 outline-none transition placeholder:text-slate-400"
                  placeholder="password"
                  type="password"
                  onChange={(e) => {
                    setPassword(e.target.value);
                  }}
                />
                <button
                  class="flex items-center justify-center gap-x-2 rounded-md border border-slate-600 bg-slate-700 py-3 px-4 text-slate-300 transition hover:text-purple-400"
                  onClick={signInWithEmail}
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="18"
                    height="18"
                    fill="currentColor"
                    class="bi bi-envelope"
                    viewBox="0 0 16 16"
                  >
                    <path
                      d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"
                      fill="#cbd5e1"
                    ></path>
                  </svg>
                  Sign in with Email
                </button>
              </div>
            )}

            {/* <div class="my-3 flex items-center px-3">
              <hr class="w-full border-slate-600" />
              <span class="mx-3 text-slate-500">or</span>
              <hr class="w-full border-slate-600" />
            </div> */}
          </div>
        </div>
      </div>
    </>
  );
}
